//! Verilog-2005 emitter — Phase 1, work item 5.
//!
//! Deliberately dumb and readable (architecture invariant #6): widths are
//! emitted symbolically (`[WIDTH-1:0]`), so module parameters pass straight
//! through to Verilog parameters with no const evaluation.
//!
//! Module layout:
//! - `mod.rs`    — `Project` symbol table, `emit` entry, `Emitter` state, shared helpers
//! - `module.rs` — module shells, ports, instances, always-blocks
//! - `expr.rs`   — expression rendering (incl. match → ternary chains)
//!
//! Not yet supported here (clean errors, not wrong output): `repeat`
//! unrolling, non-ASCII identifiers (Verilog is ASCII-only), `trunc` on
//! non-trivial expressions.

mod expr;
mod module;

use std::collections::HashMap;

use crate::ast::*;
use crate::diag::Diag;

pub struct Project<'a> {
    /// All modules across the entry file + imports, by name.
    pub modules: HashMap<String, &'a Module>,
    /// All enums (file-level and module-level), by name.
    pub enums: HashMap<String, &'a EnumDecl>,
}

impl<'a> Project<'a> {
    pub fn from_files(files: &'a [File]) -> Result<Self, Vec<Diag>> {
        let mut modules = HashMap::new();
        let mut enums = HashMap::new();
        let mut diags = Vec::new();
        for file in files {
            for item in &file.items {
                match item {
                    TopItem::Module(m) => {
                        if modules.insert(m.name.name.clone(), m).is_some() {
                            diags.push(
                                Diag::new(m.name.span, format!("module `{}` is defined twice", m.name.name))
                                    .with_help("module names must be unique across the whole project (spec/02 §1.5)"),
                            );
                        }
                        for mi in &m.items {
                            if let ModuleItem::Enum(e) = mi {
                                enums.insert(e.name.name.clone(), e);
                            }
                        }
                    }
                    TopItem::Enum(e) => {
                        enums.insert(e.name.name.clone(), e);
                    }
                    _ => {}
                }
            }
        }
        if diags.is_empty() {
            Ok(Project { modules, enums })
        } else {
            Err(diags)
        }
    }
}

pub fn emit(project: &Project, files: &[File]) -> Result<String, Vec<Diag>> {
    let mut em = Emitter {
        project,
        out: String::new(),
        diags: Vec::new(),
    };
    em.out.push_str(&format!(
        "// Generated by mimz {} — Min-Mozhi (மின்மொழி). Do not edit.\n\n",
        env!("CARGO_PKG_VERSION")
    ));
    for file in files {
        for item in &file.items {
            if let TopItem::Module(m) = item {
                em.module(m);
                em.out.push('\n');
            }
        }
    }
    if em.diags.is_empty() {
        Ok(em.out)
    } else {
        Err(em.diags)
    }
}

struct Emitter<'a> {
    project: &'a Project<'a>,
    out: String,
    diags: Vec<Diag>,
}

impl Emitter<'_> {
    fn err(&mut self, span: crate::span::Span, msg: impl Into<String>, help: &str) {
        let mut d = Diag::new(span, msg);
        if !help.is_empty() {
            d = d.with_help(help.to_string());
        }
        self.diags.push(d);
    }

    fn check_ascii(&mut self, id: &Ident) -> bool {
        if id.name.is_ascii() {
            true
        } else {
            self.err(
                id.span,
                format!(
                    "`{}` — non-ASCII identifiers are not yet supported by the Verilog emitter",
                    id.name
                ),
                "Verilog identifiers are ASCII-only; an automatic transliteration pass is planned. For now use an ASCII name",
            );
            false
        }
    }
}

/// Bits needed to encode `n` variants (≥ 1).
fn clog2(n: usize) -> u32 {
    if n <= 1 {
        1
    } else {
        usize::BITS - (n - 1).leading_zeros()
    }
}

fn enum_const(enum_name: &str, variant: &str) -> String {
    format!("{}_{}", enum_name.to_uppercase(), variant.to_uppercase())
}

/// Render an integer literal, preserving the writer's chosen base.
fn verilog_literal(value: u128, raw: &str) -> String {
    if let Some(bin) = raw.strip_prefix("0b") {
        format!("'b{bin}")
    } else if let Some(hex) = raw.strip_prefix("0x") {
        format!("'h{hex}")
    } else {
        format!("{value}")
    }
}
