//! Verilog-2005 emitter — Phase 1, work item 5.
//!
//! Deliberately dumb and readable (architecture invariant #6): widths are
//! emitted symbolically (`[WIDTH-1:0]`), so module parameters pass straight
//! through to Verilog parameters with no const evaluation.
//!
//! Module layout:
//! - `mod.rs`    — `Project` symbol table, `emit` entry, `Emitter` state, shared helpers
//! - `module.rs` — module shells, ports, instances, always-blocks
//! - `expr.rs`   — expression rendering (incl. match → ternary chains)
//!
//! Not yet supported here (clean errors, not wrong output): `repeat`
//! unrolling, non-ASCII identifiers (Verilog is ASCII-only), `trunc` on
//! non-trivial expressions.

mod expr;
mod module;

use std::collections::HashMap;

use crate::ast::*;
use crate::diag::Diag;

/// Project-wide symbol table: every module and enum by name, borrowed
/// from the parsed files. This is what lets `let u = Adder(...)` find
/// `Adder` regardless of which imported file defines it.
pub struct Project<'a> {
    /// All modules across the entry file + imports, by name.
    pub modules: HashMap<String, &'a Module>,
    /// All enums (file-level and module-level), by name.
    pub enums: HashMap<String, &'a EnumDecl>,
}

impl<'a> Project<'a> {
    /// Build the table, rejecting duplicate module names (module names are
    /// project-unique — spec/02 section 1.5). Diagnostics carry the index
    /// of the file holding the offending definition.
    pub fn from_files(files: &'a [File]) -> Result<Self, Vec<Diag>> {
        let mut modules = HashMap::new();
        let mut enums = HashMap::new();
        let mut diags = Vec::new();
        for (file_idx, file) in files.iter().enumerate() {
            for item in &file.items {
                match item {
                    TopItem::Module(m) => {
                        if modules.insert(m.name.name.clone(), m).is_some() {
                            diags.push(
                                Diag::new(m.name.span, format!("module `{}` is defined twice", m.name.name))
                                    .with_help("module names must be unique across the whole project (spec/02 section 1.5)")
                                    .with_file(file_idx),
                            );
                        }
                        for mi in &m.items {
                            if let ModuleItem::Enum(e) = mi {
                                enums.insert(e.name.name.clone(), e);
                            }
                        }
                    }
                    TopItem::Enum(e) => {
                        enums.insert(e.name.name.clone(), e);
                    }
                    _ => {}
                }
            }
        }
        if diags.is_empty() {
            Ok(Project { modules, enums })
        } else {
            Err(diags)
        }
    }
}

/// Emit all modules of all files into ONE Verilog source string (one `.v`
/// output per `mimz compile`, header comment included). Errors are
/// collected across modules — one bad module doesn't hide the others.
pub fn emit(project: &Project, files: &[File]) -> Result<String, Vec<Diag>> {
    let mut em = Emitter {
        project,
        out: String::new(),
        diags: Vec::new(),
        cur_file: 0,
    };
    em.out.push_str(&format!(
        "// Generated by mimz {} — Min-Mozhi (மின்மொழி). Do not edit.\n\n",
        env!("CARGO_PKG_VERSION")
    ));
    for (file_idx, file) in files.iter().enumerate() {
        em.cur_file = file_idx;
        for item in &file.items {
            if let TopItem::Module(m) = item {
                em.module(m);
                em.out.push('\n');
            }
        }
    }
    if em.diags.is_empty() {
        Ok(em.out)
    } else {
        Err(em.diags)
    }
}

/// Emitter state: the symbol table to look up modules/enums, the growing
/// output text, and collected errors. Emission continues after an error
/// (output is discarded if any error was recorded).
struct Emitter<'a> {
    project: &'a Project<'a>,
    out: String,
    diags: Vec<Diag>,
    /// Index of the file whose modules are currently being emitted —
    /// stamped onto every diagnostic so errors in imported files render
    /// against the right source (see `project::render_diags`).
    cur_file: usize,
}

impl Emitter<'_> {
    /// Record an error; empty `help` means no help line. The current
    /// file index is stamped automatically — emitter errors always point
    /// into the file being emitted (instance errors use the parent's
    /// spans, not the child's).
    fn err(&mut self, span: crate::span::Span, msg: impl Into<String>, help: &str) {
        let mut d = Diag::new(span, msg).with_file(self.cur_file);
        if !help.is_empty() {
            d = d.with_help(help.to_string());
        }
        self.diags.push(d);
    }

    /// Verilog identifiers are ASCII-only; Tamil-script names (legal in
    /// Min-Mozhi) get a clean error here until a transliteration pass
    /// exists. Returns whether the name is usable.
    fn check_ascii(&mut self, id: &Ident) -> bool {
        if id.name.is_ascii() {
            true
        } else {
            self.err(
                id.span,
                format!(
                    "`{}` — non-ASCII identifiers are not yet supported by the Verilog emitter",
                    id.name
                ),
                "Verilog identifiers are ASCII-only; an automatic transliteration pass is planned. For now use an ASCII name",
            );
            false
        }
    }
}

/// Bits needed to encode `n` variants (≥ 1).
fn clog2(n: usize) -> u32 {
    if n <= 1 {
        1
    } else {
        usize::BITS - (n - 1).leading_zeros()
    }
}

/// Verilog localparam name for an enum variant: `State.Red` → `STATE_RED`.
fn enum_const(enum_name: &str, variant: &str) -> String {
    format!("{}_{}", enum_name.to_uppercase(), variant.to_uppercase())
}

/// Render an integer literal, preserving the writer's chosen base.
fn verilog_literal(value: u128, raw: &str) -> String {
    if let Some(bin) = raw.strip_prefix("0b") {
        format!("'b{bin}")
    } else if let Some(hex) = raw.strip_prefix("0x") {
        format!("'h{hex}")
    } else {
        format!("{value}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{lexer, parser};

    fn parse(src: &str) -> File {
        parser::parse(lexer::lex(src).unwrap()).unwrap()
    }

    /// Project-level diagnostics must say WHICH file they point into —
    /// `render_diags` uses this to pick the right source excerpt.
    #[test]
    fn diags_carry_the_file_index() {
        // Duplicate module: file 0 defines `A`, file 1 redefines it.
        let files = [parse("module A {\n}\n"), parse("module A {\n}\n")];
        let diags = Project::from_files(&files).err().expect("duplicate");
        assert_eq!(diags[0].file, Some(1), "error is in the second file");

        // Emitter error (`repeat` unsupported) inside the second file.
        let files = [
            parse("module A {\n}\n"),
            parse("module B {\n  out led: bits[4]\n  repeat i: 0..4 {\n    led[i] = 0\n  }\n}\n"),
        ];
        let project = Project::from_files(&files).unwrap();
        let diags = emit(&project, &files).expect_err("repeat unsupported");
        assert_eq!(diags[0].file, Some(1), "error is in the second file");
    }
}
