//! Emits standard Verilog testbenches from inline `test` blocks.
//!
//! Provides `emit_testbench` which generates a `_tb.v` file containing
//! a Verilog module that instantiates the DUT, drives its inputs,
//! and evaluates `expect` statements using self-checking `$display` messages.

use crate::ast::{Dir, ModuleItem, TestDecl, TestStmt, Type};
use crate::checker::consteval::{self, Env};
use crate::diag::Diag;
use crate::emit_verilog::{Emitter, Project, REPEAT_BUDGET};
use std::collections::HashMap;

/// Sanitizes a string for use as a Verilog identifier.
/// Replaces non-alphanumeric characters with `_` and prefixes with `_` if it starts with a digit.
fn sanitize_verilog_ident(name: &str) -> String {
    if name.is_empty() {
        return String::from("_empty");
    }
    let mut safe = String::with_capacity(name.len() + 1);
    let mut chars = name.chars();
    if let Some(c) = chars.next() {
        if c.is_ascii_digit() {
            safe.push('_');
        }
        if c.is_ascii_alphanumeric() {
            safe.push(c);
        } else {
            safe.push('_');
        }
    }
    for c in chars {
        if c.is_ascii_alphanumeric() {
            safe.push(c);
        } else {
            safe.push('_');
        }
    }
    safe
}

/// Recursively emits test statements.
fn emit_test_stmts(em: &mut Emitter, stmts: &[TestStmt], indent: &str) {
    for stmt in stmts {
        match stmt {
            TestStmt::Drive { name, value } => {
                let val_str = em.expr(value);
                em.out.push_str(&format!(
                    "{}{} = {};\n",
                    indent,
                    sanitize_verilog_ident(&name.name),
                    val_str
                ));
            }
            TestStmt::Tick { clock, count } => {
                let count_val = count
                    .as_ref()
                    .and_then(|c| match consteval::eval(c, &Env::new()) {
                        Ok(v) => Some(v),
                        Err(e) => {
                            em.diags.push(e);
                            None
                        }
                    })
                    .unwrap_or(1);
                // Clamp count_val to prevent simulator hangs
                let count_val = count_val.clamp(1, 1_000_000);
                em.out.push_str(&format!(
                    "{}repeat ({}) @(posedge {});\n",
                    indent,
                    count_val,
                    sanitize_verilog_ident(&clock.name)
                ));
            }
            TestStmt::Expect(e) => {
                let cond_str = em.expr(e);
                em.out
                    .push_str(&format!("{}if (!({})) begin\n", indent, cond_str));
                em.out.push_str(&format!(
                    "{}  $display(\"FAIL: expect %0s failed\", \"{}\");\n",
                    indent,
                    cond_str.replace('\"', "\\\"")
                ));
                em.out.push_str(&format!("{}  $finish;\n", indent));
                em.out.push_str(&format!("{}end\n", indent));
            }
            TestStmt::If { cond, then, els } => {
                let cond_str = em.expr(cond);
                em.out
                    .push_str(&format!("{}if ({}) begin\n", indent, cond_str));
                let next_indent = format!("{}  ", indent);
                emit_test_stmts(em, then, &next_indent);
                if let Some(else_stmts) = els {
                    em.out.push_str(&format!("{}end else begin\n", indent));
                    emit_test_stmts(em, else_stmts, &next_indent);
                }
                em.out.push_str(&format!("{}end\n", indent));
            }
            // Unreachable on the codegen path: `parse` rejects a tree with any
            // `Error` node, so testbench emission never sees one.
            TestStmt::Error(_) => {}
        }
    }
}

/// Generates a Verilog testbench string for the given inline test declarations.
pub fn emit_testbench(project: &Project, tests: &[&TestDecl]) -> Result<String, Vec<Diag>> {
    let mut em = Emitter {
        project,
        out: String::new(),
        diags: Vec::new(),
        cur_file: 0,
        env: Env::new(),
        module_envs: HashMap::new(),
        repeat_budget: REPEAT_BUDGET,
        clog2_fn_used: false,
        emitting_port: false,
        funcs_used: Vec::new(),
        bundle_sigs: HashMap::new(),
    };

    em.out.push_str(&format!(
        "// Generated by mimz {} (edition {}) — Min-Mozhi (மின்மொழி) Testbench. Do not edit.\n\n",
        crate::version::COMPILER_VERSION,
        crate::version::current().tag()
    ));

    let mut seen_tb_names: HashMap<String, String> = HashMap::new();

    for test in tests {
        let span = test.span;

        let dut = match project.modules.get(&test.module.name) {
            Some(m) => m,
            None => {
                em.diags.push(Diag::new(
                    span,
                    format!("module `{}` not found for test", test.module.name),
                ));
                continue;
            }
        };

        let safe_name = sanitize_verilog_ident(&test.name);
        let base = if safe_name == "_empty" {
            "test"
        } else {
            &safe_name
        };
        let tb_name = format!("{}_tb", base);

        // Two differently-named tests can sanitize to the same Verilog
        // identifier (e.g. "edge case" and "edge_case" both -> `edge_case_tb`),
        // which would otherwise emit two `module edge_case_tb` blocks into the
        // same file. Catch it as a clear diagnostic instead of broken Verilog.
        if let Some(prev_name) = seen_tb_names.get(&tb_name) {
            em.diags.push(Diag::new(
                span,
                format!(
                    "test \"{}\" and test \"{}\" both sanitize to the Verilog module \
                     name `{tb_name}` — rename one test",
                    prev_name, test.name
                ),
            ));
            continue;
        }
        seen_tb_names.insert(tb_name.clone(), test.name.clone());

        em.out.push_str(&format!("module {};\n", tb_name));

        // Resolve explicit test args first — each may reference an earlier one
        // (e.g. `M(W: 8, DEPTH: W * 2)`), same as `sim::harness::params` — then
        // fall back to the module's own parameter defaults for anything the
        // test didn't override, same order/semantics as
        // `sim::elaborate::elaborate_module`. Without this, a width expression
        // like `bits[W]` fails to resolve whenever a test omits a parameter
        // that has a module-level default.
        let mut test_env = Env::new();
        for a in &test.args {
            match consteval::eval(&a.value, &test_env) {
                Ok(v) => {
                    test_env.insert(a.name.name.clone(), v);
                }
                Err(e) => {
                    em.diags.push(e);
                }
            }
        }
        for p in &dut.params {
            if test_env.contains_key(&p.name.name) {
                continue;
            }
            match &p.default {
                Some(d) => match consteval::eval(d, &test_env) {
                    Ok(v) => {
                        test_env.insert(p.name.name.clone(), v);
                    }
                    Err(e) => em.diags.push(e),
                },
                None => em.diags.push(Diag::new(
                    span,
                    format!(
                        "parameter `{}` has no default — provide a value for it in the test",
                        p.name.name
                    ),
                )),
            }
        }

        let mut dut_connections = Vec::new();

        for item in &dut.items {
            match item {
                ModuleItem::Port { dir, name, ty } => {
                    let kind = if *dir == Dir::In { "reg" } else { "wire" };
                    let width_str = match ty {
                        Type::Bit => String::new(),
                        Type::Bits(e) | Type::Signed(e) => {
                            match consteval::eval(e.as_ref(), &test_env) {
                                Ok(v) => {
                                    if v > 1 {
                                        format!("[{}-1:0] ", v)
                                    } else {
                                        String::new()
                                    }
                                }
                                Err(e) => {
                                    em.diags.push(e);
                                    String::new()
                                }
                            }
                        }
                        Type::Named(_) => String::new(),
                        Type::Bundle { .. } => todo!(),
                    };
                    let signed = if matches!(ty, Type::Signed(_)) {
                        "signed "
                    } else {
                        ""
                    };
                    let safe_port_name = sanitize_verilog_ident(&name.name);
                    em.out.push_str(&format!(
                        "  {} {}{}{};\n",
                        kind, signed, width_str, safe_port_name
                    ));
                    dut_connections.push(format!(".{}({})", safe_port_name, safe_port_name));
                }
                ModuleItem::Clock(c) => {
                    let safe_clock = sanitize_verilog_ident(&c.name);
                    em.out.push_str(&format!("  reg {};\n", safe_clock));
                    dut_connections.push(format!(".{}({})", safe_clock, safe_clock));
                }
                ModuleItem::Reset { name, .. } => {
                    let safe_reset = sanitize_verilog_ident(&name.name);
                    em.out.push_str(&format!("  reg {};\n", safe_reset));
                    dut_connections.push(format!(".{}({})", safe_reset, safe_reset));
                }
                _ => {}
            }
        }

        em.out.push('\n');

        let param_str = if test.args.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = test
                .args
                .iter()
                .map(|a| {
                    let val = em.expr(&a.value);
                    format!(".{}({})", sanitize_verilog_ident(&a.name.name), val)
                })
                .collect();
            format!(" #({})", params.join(", "))
        };

        let space_before_param = if param_str.is_empty() { "" } else { " " };
        em.out.push_str(&format!(
            "  {}{}{} _dut_inst (\n    {}\n  );\n\n",
            sanitize_verilog_ident(&dut.name.name),
            space_before_param,
            param_str,
            dut_connections.join(",\n    ")
        ));

        for item in &dut.items {
            if let ModuleItem::Clock(c) = item {
                let safe_clock = sanitize_verilog_ident(&c.name);
                em.out.push_str(&format!("  initial {} = 0;\n", safe_clock));
                em.out
                    .push_str(&format!("  always #5 {} = ~{};\n", safe_clock, safe_clock));
            }
        }
        em.out.push('\n');

        em.out.push_str("  initial begin\n");
        em.out
            .push_str(&format!("    $dumpfile(\"{}.vcd\");\n", tb_name));
        em.out
            .push_str(&format!("    $dumpvars(0, {});\n", tb_name));

        for item in &dut.items {
            if let ModuleItem::Port { dir, name, .. } = item {
                if *dir == Dir::In {
                    em.out.push_str(&format!(
                        "    {} = 0;\n",
                        sanitize_verilog_ident(&name.name)
                    ));
                }
            }
            if let ModuleItem::Reset { name, .. } = item {
                em.out.push_str(&format!(
                    "    {} = 0;\n",
                    sanitize_verilog_ident(&name.name)
                ));
            }
        }

        emit_test_stmts(&mut em, &test.body, "    ");

        em.out.push_str("    $display(\"PASS\");\n");
        em.out.push_str("    $finish;\n");
        em.out.push_str("  end\n");
        em.out.push_str("endmodule\n\n");
    }

    if em.diags.is_empty() {
        Ok(em.out)
    } else {
        Err(em.diags)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{checker, lexer, parser};

    #[test]
    fn sanitize_verilog_ident_replaces_invalid_chars() {
        assert_eq!(sanitize_verilog_ident("valid_name"), "valid_name");
        assert_eq!(sanitize_verilog_ident("1invalid"), "_1invalid");
        assert_eq!(sanitize_verilog_ident("has spaces"), "has_spaces");
        assert_eq!(sanitize_verilog_ident("with!sym"), "with_sym");
        assert_eq!(sanitize_verilog_ident(""), "_empty");
    }

    /// The same single-file pipeline `mimz compile --emit-testbench` runs
    /// (`src/commands/compile.rs`): lex, parse, check, transliterate, then emit.
    fn compile_tb(src: &str) -> Result<String, Vec<Diag>> {
        let toks = lexer::lex(src)?;
        let ast = parser::parse(toks)?;
        let mut asts = vec![ast];
        checker::check(&asts)?;
        crate::emit_verilog::transliterate(&mut asts);
        let project = crate::emit_verilog::Project::from_files(&asts)?;
        let tests: Vec<&TestDecl> = asts
            .iter()
            .flat_map(|f| {
                f.items.iter().filter_map(|i| match i {
                    crate::ast::TopItem::Test(t) => Some(t),
                    _ => None,
                })
            })
            .collect();
        emit_testbench(&project, &tests)
    }

    /// A test that doesn't override a module parameter must still resolve
    /// width expressions using the module's own default — mirrors
    /// `sim::elaborate::elaborate_module`'s override-or-default merge, which
    /// `mimz test`/`mimz sim` already rely on.
    #[test]
    fn test_env_falls_back_to_module_param_defaults() {
        let src = "\
module Adder(WIDTH: int = 8) {
  in a: bits[WIDTH]
  in b: bits[WIDTH]
  out sum: bits[WIDTH + 1]
  sum = a + b
}

test \"adder defaults\" for Adder {
  a = 5
  b = 10
  expect sum == 15
}
";
        let tb = compile_tb(src)
            .unwrap_or_else(|d| panic!("expected the WIDTH default (8) to resolve: {d:?}"));
        assert!(
            tb.contains("[8-1:0]"),
            "expected ports sized by the default WIDTH=8, got:\n{tb}"
        );
    }

    /// A later test argument may reference an earlier one in the same
    /// `for Module(...)` argument list.
    #[test]
    fn test_env_chains_earlier_args() {
        let src = "\
module Adder(WIDTH: int = 8, DOUBLE: int = 1) {
  in a: bits[WIDTH]
  out y: bits[WIDTH]
  y = a
}

test \"chained args\" for Adder(WIDTH: 4, DOUBLE: WIDTH * 2) {
  a = 1
  expect y == 1
}
";
        let tb = compile_tb(src).unwrap_or_else(|d| {
            panic!("expected DOUBLE: WIDTH * 2 to resolve against the already-bound WIDTH: {d:?}")
        });
        assert!(
            tb.contains("[4-1:0]"),
            "expected ports sized by WIDTH=4, got:\n{tb}"
        );
    }

    /// Two tests whose names sanitize to the same Verilog module identifier
    /// must be rejected with a clear diagnostic, not silently emitted as two
    /// `module edge_case_tb` blocks in the same file.
    #[test]
    fn colliding_sanitized_test_names_are_rejected() {
        let src = "\
module Buf {
  in a: bit
  out y: bit
  y = a
}

test \"edge case\" for Buf {
  a = 1
  expect y == 1
}

test \"edge_case\" for Buf {
  a = 0
  expect y == 0
}
";
        let diags = compile_tb(src).expect_err("colliding sanitized names must error");
        assert!(
            diags.iter().any(|d| d.msg.contains("edge_case_tb")),
            "expected a collision diagnostic naming `edge_case_tb`, got: {diags:?}"
        );
    }
}
