//! Emits standard Verilog testbenches from inline `test` blocks.
//!
//! Provides `emit_testbench` which generates a `_tb.v` file containing
//! a Verilog module that instantiates the DUT, drives its inputs,
//! and evaluates `expect` statements using self-checking `$display` messages.

use crate::ast::{Dir, ModuleItem, TestDecl, TestStmt, Type};
use crate::checker::consteval::{self, Env};
use crate::diag::Diag;
use crate::emit_verilog::{Emitter, Project, REPEAT_BUDGET};
use std::collections::HashMap;

/// Sanitizes a string for use as a Verilog identifier.
/// Replaces non-alphanumeric characters with `_` and prefixes with `_` if it starts with a digit.
fn sanitize_verilog_ident(name: &str) -> String {
    if name.is_empty() {
        return String::from("_empty");
    }
    let mut safe = String::with_capacity(name.len() + 1);
    let mut chars = name.chars();
    if let Some(c) = chars.next() {
        if c.is_ascii_digit() {
            safe.push('_');
        }
        if c.is_ascii_alphanumeric() {
            safe.push(c);
        } else {
            safe.push('_');
        }
    }
    for c in chars {
        if c.is_ascii_alphanumeric() {
            safe.push(c);
        } else {
            safe.push('_');
        }
    }
    safe
}

/// Recursively emits test statements.
fn emit_test_stmts(em: &mut Emitter, stmts: &[TestStmt], indent: &str) {
    for stmt in stmts {
        match stmt {
            TestStmt::Drive { name, value } => {
                let val_str = em.expr(value);
                em.out.push_str(&format!(
                    "{}{} = {};\n",
                    indent,
                    sanitize_verilog_ident(&name.name),
                    val_str
                ));
            }
            TestStmt::Tick { clock, count } => {
                let count_val = count
                    .as_ref()
                    .and_then(|c| match consteval::eval(c, &Env::new()) {
                        Ok(v) => Some(v),
                        Err(e) => {
                            em.diags.push(e);
                            None
                        }
                    })
                    .unwrap_or(1);
                // Clamp count_val to prevent simulator hangs
                let count_val = count_val.clamp(1, 1_000_000);
                em.out.push_str(&format!(
                    "{}repeat ({}) @(posedge {});\n",
                    indent,
                    count_val,
                    sanitize_verilog_ident(&clock.name)
                ));
            }
            TestStmt::Expect(e) => {
                let cond_str = em.expr(e);
                em.out
                    .push_str(&format!("{}if (!({})) begin\n", indent, cond_str));
                em.out.push_str(&format!(
                    "{}  $display(\"FAIL: expect %0s failed\", \"{}\");\n",
                    indent,
                    cond_str.replace('\"', "\\\"")
                ));
                em.out.push_str(&format!("{}  $finish;\n", indent));
                em.out.push_str(&format!("{}end\n", indent));
            }
            TestStmt::If { cond, then, els } => {
                let cond_str = em.expr(cond);
                em.out
                    .push_str(&format!("{}if ({}) begin\n", indent, cond_str));
                let next_indent = format!("{}  ", indent);
                emit_test_stmts(em, then, &next_indent);
                if let Some(else_stmts) = els {
                    em.out.push_str(&format!("{}end else begin\n", indent));
                    emit_test_stmts(em, else_stmts, &next_indent);
                }
                em.out.push_str(&format!("{}end\n", indent));
            }
        }
    }
}

/// Generates a Verilog testbench string for the given inline test declarations.
pub fn emit_testbench(project: &Project, tests: &[&TestDecl]) -> Result<String, Vec<Diag>> {
    let mut em = Emitter {
        project,
        out: String::new(),
        diags: Vec::new(),
        cur_file: 0,
        env: Env::new(),
        module_envs: HashMap::new(),
        repeat_budget: REPEAT_BUDGET,
    };

    em.out.push_str(&format!(
        "// Generated by mimz {} (edition {}) — Min-Mozhi (மின்மொழி) Testbench. Do not edit.\n\n",
        crate::version::COMPILER_VERSION,
        crate::version::current().tag()
    ));

    for test in tests {
        let span = test.span;

        let dut = match project.modules.get(&test.module.name) {
            Some(m) => m,
            None => {
                em.diags.push(Diag::new(
                    span,
                    format!("module `{}` not found for test", test.module.name),
                ));
                continue;
            }
        };

        let safe_name = sanitize_verilog_ident(&test.name);
        let base = if safe_name.is_empty() || safe_name == "_empty" {
            "test"
        } else {
            &safe_name
        };
        let tb_name = format!("{}_tb", base);

        em.out.push_str(&format!("module {};\n", tb_name));

        let mut test_env = Env::new();
        for a in &test.args {
            match consteval::eval(&a.value, &Env::new()) {
                Ok(v) => {
                    test_env.insert(a.name.name.clone(), v);
                }
                Err(e) => {
                    em.diags.push(e);
                }
            }
        }

        let mut dut_connections = Vec::new();

        for item in &dut.items {
            match item {
                ModuleItem::Port { dir, name, ty } => {
                    let kind = if *dir == Dir::In { "reg" } else { "wire" };
                    let width_str = match ty {
                        Type::Bit => String::new(),
                        Type::Bits(e) | Type::Signed(e) => {
                            match consteval::eval(e.as_ref(), &test_env) {
                                Ok(v) => {
                                    if v > 1 {
                                        format!("[{}-1:0] ", v)
                                    } else {
                                        String::new()
                                    }
                                }
                                Err(e) => {
                                    em.diags.push(e);
                                    String::new()
                                }
                            }
                        }
                        Type::Named(_) => String::new(),
                    };
                    let signed = if matches!(ty, Type::Signed(_)) {
                        "signed "
                    } else {
                        ""
                    };
                    let safe_port_name = sanitize_verilog_ident(&name.name);
                    em.out.push_str(&format!(
                        "  {} {}{}{};\n",
                        kind, signed, width_str, safe_port_name
                    ));
                    dut_connections.push(format!(".{}({})", safe_port_name, safe_port_name));
                }
                ModuleItem::Clock(c) => {
                    let safe_clock = sanitize_verilog_ident(&c.name);
                    em.out.push_str(&format!("  reg {};\n", safe_clock));
                    dut_connections.push(format!(".{}({})", safe_clock, safe_clock));
                }
                ModuleItem::Reset { name, .. } => {
                    let safe_reset = sanitize_verilog_ident(&name.name);
                    em.out.push_str(&format!("  reg {};\n", safe_reset));
                    dut_connections.push(format!(".{}({})", safe_reset, safe_reset));
                }
                _ => {}
            }
        }

        em.out.push('\n');

        let param_str = if test.args.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = test
                .args
                .iter()
                .map(|a| {
                    let val = em.expr(&a.value);
                    format!(".{}({})", sanitize_verilog_ident(&a.name.name), val)
                })
                .collect();
            format!(" #({})", params.join(", "))
        };

        em.out.push_str(&format!(
            "  {} {} _dut_inst (\n    {}\n  );\n\n",
            sanitize_verilog_ident(&dut.name.name),
            param_str,
            dut_connections.join(",\n    ")
        ));

        for item in &dut.items {
            if let ModuleItem::Clock(c) = item {
                let safe_clock = sanitize_verilog_ident(&c.name);
                em.out.push_str(&format!("  initial {} = 0;\n", safe_clock));
                em.out
                    .push_str(&format!("  always #5 {} = ~{};\n", safe_clock, safe_clock));
            }
        }
        em.out.push('\n');

        em.out.push_str("  initial begin\n");
        em.out
            .push_str(&format!("    $dumpfile(\"{}.vcd\");\n", tb_name));
        em.out
            .push_str(&format!("    $dumpvars(0, {});\n", tb_name));

        for item in &dut.items {
            if let ModuleItem::Port { dir, name, .. } = item {
                if *dir == Dir::In {
                    em.out.push_str(&format!(
                        "    {} = 0;\n",
                        sanitize_verilog_ident(&name.name)
                    ));
                }
            }
            if let ModuleItem::Reset { name, .. } = item {
                em.out.push_str(&format!(
                    "    {} = 0;\n",
                    sanitize_verilog_ident(&name.name)
                ));
            }
        }

        emit_test_stmts(&mut em, &test.body, "    ");

        em.out.push_str("    $display(\"PASS\");\n");
        em.out.push_str("    $finish;\n");
        em.out.push_str("  end\n");
        em.out.push_str("endmodule\n\n");
    }

    if em.diags.is_empty() {
        Ok(em.out)
    } else {
        Err(em.diags)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_verilog_ident_replaces_invalid_chars() {
        assert_eq!(sanitize_verilog_ident("valid_name"), "valid_name");
        assert_eq!(sanitize_verilog_ident("1invalid"), "_1invalid");
        assert_eq!(sanitize_verilog_ident("has spaces"), "has_spaces");
        assert_eq!(sanitize_verilog_ident("with!sym"), "with_sym");
        assert_eq!(sanitize_verilog_ident(""), "_empty");
    }
}
