//! Tests for the in-memory `mimz::compile_string` entry point (the embedding
//! API behind the WASM playground). It runs the full pipeline on a source
//! string with no filesystem access — so these assert behavior the browser sees.

use std::path::PathBuf;

use mimz::compile_string;

/// Drop the `// Generated by mimz ...` banner line so version bumps don't
/// churn the golden file.
fn strip_banner(v: &str) -> String {
    let mut lines = v.lines();
    let first = lines.next().unwrap_or("");
    if first.starts_with("// Generated by mimz") {
        let rest: Vec<&str> = lines.collect();
        format!("{}\n", rest.join("\n").trim_start_matches('\n'))
    } else {
        v.replace("\r\n", "\n")
    }
}

/// A valid combinational module compiles to Verilog naming that module.
#[test]
fn compiles_valid_module_to_verilog() {
    let src = "\
module And2 {
  in a: bit
  in b: bit
  out y: bit
  y = a and b
}
";
    let verilog = compile_string(src).expect("And2 should compile");
    assert!(verilog.contains("module And2"), "got:\n{verilog}");
    // The generated header marks it as mimz output (not hand-written Verilog).
    assert!(
        verilog.contains("mimz"),
        "expected generator banner, got:\n{verilog}"
    );
}

/// The trilingual thesis holds through the in-memory path too: the same circuit
/// in Tamil keywords yields byte-identical Verilog to the English source.
#[test]
fn tamil_and_english_emit_identical_verilog() {
    let english = "\
module Buf {
  in a: bit
  out y: bit
  y = a
}
";
    let tamil = "\
தொகுதி Buf {
  உள்ளீடு a: bit
  வெளியீடு y: bit
  y = a
}
";
    let en = compile_string(english).expect("english compiles");
    let ta = compile_string(tamil).expect("tamil compiles");
    assert_eq!(en, ta, "trilingual output must be byte-identical");
}

/// A checker error (width mismatch) comes back as rendered diagnostics carrying
/// the stable E-code, not as Verilog.
#[test]
fn width_mismatch_returns_rendered_diagnostic() {
    let src = "\
module Narrow {
  in a: bits[4]
  out y: bits[2]
  y = a
}
";
    let err = compile_string(src).expect_err("width mismatch must fail");
    assert!(err.contains("E0401"), "expected E0401 in:\n{err}");
}

/// A lexer/parser error is reported (rendered), not silently dropped.
#[test]
fn syntax_error_is_reported() {
    let err = compile_string("module {").expect_err("garbage must fail");
    assert!(!err.is_empty(), "a syntax error should render a message");
}

/// `import` cannot be resolved in single-file mode and is rejected with a clear
/// message (no file system to resolve against).
#[test]
fn import_is_rejected() {
    let src = "\
import lib.adder
module M {
  in a: bit
  out y: bit
  y = a
}
";
    let err = compile_string(src).expect_err("import must be rejected");
    assert!(
        err.contains("import"),
        "expected an import message in:\n{err}"
    );
}

/// Compile source expecting success; panics with the diagnostic on failure.
fn compile_ok(src: &str) -> String {
    compile_string(src).unwrap_or_else(|e| panic!("compile_ok failed:\n{e}"))
}

#[test]
fn emit_bundle_port_flattens() {
    let src = r#"
bundle Hs(W: int = 8) {
  valid: bit
  data: bits[W]
}
module Top {
  in  req: Hs(W: 8)
  out rsp: Hs(W: 8)
  rsp = req
}
"#;
    let verilog = compile_ok(src);
    // Ports must be flattened with prefix.
    assert!(
        verilog.contains("input wire req_valid"),
        "missing req_valid in:\n{verilog}"
    );
    assert!(
        verilog.contains("input wire [7:0] req_data"),
        "missing req_data in:\n{verilog}"
    );
    assert!(
        verilog.contains("output wire rsp_valid"),
        "missing rsp_valid in:\n{verilog}"
    );
    assert!(
        verilog.contains("output wire [7:0] rsp_data"),
        "missing rsp_data in:\n{verilog}"
    );
    // Assignments also flatten.
    assert!(
        verilog.contains("assign rsp_valid = req_valid"),
        "missing assign in:\n{verilog}"
    );
    assert!(
        verilog.contains("assign rsp_data = req_data"),
        "missing assign in:\n{verilog}"
    );
}

#[test]
fn emit_bundle_literal() {
    let src = r#"
bundle Hs { valid: bit, data: bits[8] }
module Top {
  out rsp: Hs
  rsp = { valid: 1, data: 0 }
}
"#;
    let verilog = compile_ok(src);
    assert!(
        verilog.contains("assign rsp_valid = 1'b1"),
        "missing rsp_valid:\n{verilog}"
    );
    assert!(
        verilog.contains("assign rsp_data = 8'd0"),
        "missing rsp_data:\n{verilog}"
    );
}

/// Golden-lock for the tagged-enum emitter: a `Packet` enum with two tagged
/// variants (`Read(addr)` and `Write(addr, data)`) must lower to correct
/// localparam widths, tag-bit comparisons, and payload slice extractions.
///
/// Regenerate with `MIMZ_UPDATE_GOLDENS=1 cargo test tagged_packet_golden`.
#[test]
fn tagged_packet_golden() {
    let src = "\
module Decoder {
  enum Packet { Read(addr: bits[32]), Write(addr: bits[32], data: bits[32]) }
  in bus: Packet
  out raddr: bits[32]
  raddr = match (bus) {
    Packet.Read(a)    => a
    Packet.Write(a, d) => 0
  }
}
";
    let verilog = compile_string(src).expect("tagged enum Decoder should compile");
    let got = strip_banner(&verilog);

    let golden_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("golden")
        .join("tagged_packet_decoder.v");

    if std::env::var("MIMZ_UPDATE_GOLDENS").is_ok() {
        std::fs::write(&golden_path, &got).unwrap();
        return;
    }

    let want = std::fs::read_to_string(&golden_path)
        .unwrap_or_else(|_| {
            panic!(
                "missing golden {} — run with MIMZ_UPDATE_GOLDENS=1 to create it",
                golden_path.display()
            )
        })
        .replace("\r\n", "\n");

    assert_eq!(got, want, "tagged enum Verilog differs from golden");
}

/// Guard-clause `fn` bodies must lower via continuation-passing: a `return`
/// fired inside an `if` branch must never be overwritten by the mandatory
/// tail assignment. A naive lowering appends `f = <tail>;` unconditionally
/// after the if/else, silently discarding the `return 255` path.
#[test]
fn guard_clause_return_does_not_get_overwritten_by_tail() {
    let src = "fn f(a: bits[8]) -> bits[8] {\n  if a[0] == 1 { return 255 }\n  0\n}\nmodule M {\n  in a: bits[8]\n  out o: bits[8]\n  o = f(a)\n}\n";
    let verilog = compile_ok(src);
    // The `255` assignment must be nested inside the `if`, and the fallback
    // `0` must be nested inside the corresponding `else` — NOT a bare
    // trailing `f = 0;` that runs unconditionally after the if.
    assert!(
        verilog.contains("if ((a[0] == 1)) begin"),
        "missing if guard in:\n{verilog}"
    );
    assert!(
        verilog.contains("f = 255"),
        "missing return value in:\n{verilog}"
    );
    assert!(
        verilog.contains("end else begin"),
        "missing else branch in:\n{verilog}"
    );
    assert!(
        verilog.contains("f = 0"),
        "missing tail value in:\n{verilog}"
    );
    // The bug this test guards against: a naive lowering emits `f = 0;` a
    // SECOND time, unconditionally, after the if/else block closes.
    let f_assign_count = verilog.matches("f = 0").count();
    assert_eq!(
        f_assign_count, 1,
        "the tail value must be assigned exactly once, inside the else branch \
         — a second, unconditional assignment would silently overwrite the \
         `return 255` path"
    );
}
