//! Integration tests for the grammar engine (spec/04, Phase 1.8): the
//! `syntax thamizh` word-order profile.
//!
//! The headline guarantee is **same AST, two orders**. We test it the same
//! way the four-flavor rule is tested (`examples.rs`): the backend is
//! profile-blind, so a thamizh-order file and its code-order twin must emit
//! BYTE-IDENTICAL Verilog. Equal Verilog out of a profile-blind backend means
//! the parser built the same tree from both orders — which is the contract.
//!
//! Slices landed: the clocked-block flip (`rise(clk) on { }`), the seq
//! conditional (`<cond> enil { }`), the if-expression (`c enil { } illaiyenil
//! { }`), and match (`<expr> thernthedu { }`). The test-form flip arrives with
//! Phase 1.5 (test blocks emit no Verilog yet, so they have no same-Verilog
//! oracle).

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn mimz() -> Command {
    Command::new(env!("CARGO_BIN_EXE_mimz"))
}

/// Strip the `// Generated by mimz` banner line and normalize newlines, so
/// comparisons are over the Verilog body only (mirrors `examples.rs`).
fn strip_banner(v: &str) -> String {
    let mut lines = v.lines();
    let first = lines.next().unwrap_or("");
    if first.starts_with("// Generated by mimz") {
        let rest: Vec<&str> = lines.collect();
        format!("{}\n", rest.join("\n").trim_start_matches('\n'))
    } else {
        v.replace("\r\n", "\n")
    }
}

/// Compile a `.mimz` file to Verilog text. Unique temp path per call — tests
/// run in parallel and a shared output path is a torn-read race.
fn compile(path: &Path) -> String {
    static N: AtomicUsize = AtomicUsize::new(0);
    let name = path.display().to_string().replace(['\\', '/', ':'], "_");
    let out_v = std::env::temp_dir().join(format!(
        "mimz_grammar_{}_{name}.v",
        N.fetch_add(1, Ordering::Relaxed)
    ));
    let out = mimz()
        .arg("compile")
        .arg(path)
        .arg("-o")
        .arg(&out_v)
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "`mimz compile {}` failed:\n{}",
        path.display(),
        String::from_utf8_lossy(&out.stderr)
    );
    strip_banner(&std::fs::read_to_string(&out_v).unwrap())
}

/// Compile inline source from a temp file; return (success, stderr).
fn compile_src(src: &str, tag: &str) -> (bool, String) {
    static N: AtomicUsize = AtomicUsize::new(0);
    let n = N.fetch_add(1, Ordering::Relaxed);
    let in_f = std::env::temp_dir().join(format!("mimz_grammar_src_{tag}_{n}.mimz"));
    let out_v = std::env::temp_dir().join(format!("mimz_grammar_src_{tag}_{n}.v"));
    std::fs::write(&in_f, src).unwrap();
    let out = mimz()
        .arg("compile")
        .arg(&in_f)
        .arg("-o")
        .arg(&out_v)
        .output()
        .unwrap();
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

fn fixture(name: &str) -> PathBuf {
    root().join("tests/fixtures/grammar").join(name)
}

fn example(rel: &str) -> PathBuf {
    root().join("examples").join(rel)
}

/// Same-AST guarantee: the Tanglish thamizh-order counter compiles to the
/// EXACT same Verilog as its code-order twin (`examples/tanglish/counter`).
#[test]
fn thamizh_order_counter_matches_code_order_twin() {
    let thamizh = compile(&fixture("counter.thamizh.mimz"));
    let code_order = compile(&example("tanglish/counter.mimz"));
    assert_eq!(
        thamizh, code_order,
        "thamizh-order counter must emit byte-identical Verilog to its code-order twin"
    );
}

/// The pure-Tamil-script thamizh-order counter compiles to the same Verilog
/// as the code-order Tamil counter — Tamil script AND natural word order.
#[test]
fn thamizh_order_tamil_counter_matches_code_order_twin() {
    let thamizh = compile(&fixture("counter_tamil.thamizh.mimz"));
    let code_order = compile(&example("tamil/counter.mimz"));
    assert_eq!(thamizh, code_order);
}

/// Both thamizh-order flavors agree with the canonical English golden —
/// profile and keyword skin are fully orthogonal.
#[test]
fn thamizh_order_agrees_with_english_golden() {
    let english = compile(&example("english/counter.mimz"));
    assert_eq!(compile(&fixture("counter.thamizh.mimz")), english);
    assert_eq!(compile(&fixture("counter_tamil.thamizh.mimz")), english);
}

/// `syntax <other>` is rejected with E1112, not silently ignored.
#[test]
fn unknown_syntax_profile_is_an_error() {
    let (ok, stderr) = compile_src("syntax wibble\nmodule M { in a: bit\n}\n", "badprofile");
    assert!(!ok, "an unknown syntax profile must fail to compile");
    assert!(
        stderr.contains("E1112"),
        "expected E1112 for an unknown profile, got:\n{stderr}"
    );
}

/// In code-order (no directive) a leading `rise(...)` block is NOT accepted —
/// the flip is gated on the profile, not always on.
#[test]
fn flipped_on_block_is_rejected_in_code_order() {
    let src = "module M {\n  clock clk\n  reg r: bit = 0\n  rise(clk) on {\n    r <- r\n  }\n}\n";
    let (ok, _stderr) = compile_src(src, "flip_in_code");
    assert!(
        !ok,
        "`rise(clk) on {{}}` must be a parse error without `syntax thamizh`"
    );
}

/// Seq conditional flip: the Tanglish thamizh-order blinker (clocked block +
/// `<cond> enil { } illaiyenil { }`) emits byte-identical Verilog to its
/// code-order twin.
#[test]
fn thamizh_order_blinker_matches_code_order_twin() {
    let thamizh = compile(&fixture("blinker.thamizh.mimz"));
    let code_order = compile(&example("tanglish/blinker.mimz"));
    assert_eq!(
        thamizh, code_order,
        "thamizh-order conditional must emit byte-identical Verilog to its code-order twin"
    );
}

/// The same seq-conditional flip in pure Tamil script — profile and keyword
/// flavor are orthogonal.
#[test]
fn thamizh_order_blinker_tamil_matches_code_order_twin() {
    let thamizh = compile(&fixture("blinker_tamil.thamizh.mimz"));
    let code_order = compile(&example("tamil/blinker.mimz"));
    assert_eq!(thamizh, code_order);
}

/// All three blinker flavors agree with the English golden — the SOV
/// conditional changes nothing the backend can see.
#[test]
fn thamizh_order_blinker_agrees_with_english_golden() {
    let english = compile(&example("english/blinker.mimz"));
    assert_eq!(compile(&fixture("blinker.thamizh.mimz")), english);
    assert_eq!(compile(&fixture("blinker_tamil.thamizh.mimz")), english);
}

/// If-expression flip: the thamizh-order comparator (`max = a > b enil { a }
/// illaiyenil { b }`) emits byte-identical Verilog to its code-order twin.
#[test]
fn thamizh_order_comparator_matches_code_order_twin() {
    let thamizh = compile(&fixture("comparator.thamizh.mimz"));
    let code_order = compile(&example("tanglish/comparator.mimz"));
    assert_eq!(
        thamizh, code_order,
        "thamizh-order if-expression must emit byte-identical Verilog to its code-order twin"
    );
}

/// Match flip: the thamizh-order ALU (`y = op thernthedu { … }`) emits
/// byte-identical Verilog to its code-order twin (a self-contained fixture
/// pair — the tanglish ALU example imports `adder`).
#[test]
fn thamizh_order_match_matches_code_order_twin() {
    let thamizh = compile(&fixture("match.thamizh.mimz"));
    let code_order = compile(&fixture("match.code.mimz"));
    assert_eq!(
        thamizh, code_order,
        "thamizh-order match must emit byte-identical Verilog to its code-order twin"
    );
}

/// The flipped forms are gated on the profile: without `syntax thamizh`, the
/// trailing-keyword forms (`<cond> enil`, `a > b enil { } illaiyenil { }`,
/// `op thernthedu { }`) are parse errors, not silently accepted.
#[test]
fn flipped_conditional_is_rejected_in_code_order() {
    let src = "module M {\n  clock clk\n  reg r: bit = 0\n  on rise(clk) {\n    r == 0 enil {\n      r <- 1\n    }\n  }\n}\n";
    let (ok, _stderr) = compile_src(src, "flip_cond_code");
    assert!(
        !ok,
        "`<cond> enil {{}}` must be a parse error without `syntax thamizh`"
    );
}

#[test]
fn flipped_if_expr_is_rejected_in_code_order() {
    let src = "module M {\n  in a: bit\n  in b: bit\n  out y: bit\n  y = a > b enil { a } illaiyenil { b }\n}\n";
    let (ok, _stderr) = compile_src(src, "flip_ifexpr_code");
    assert!(
        !ok,
        "`a > b enil {{ }} illaiyenil {{ }}` must be a parse error without `syntax thamizh`"
    );
}

#[test]
fn flipped_match_is_rejected_in_code_order() {
    let src = "module M {\n  in op: bits[2]\n  out y: bit\n  y = op thernthedu {\n    0b00 => 1\n    _ => 0\n  }\n}\n";
    let (ok, _stderr) = compile_src(src, "flip_match_code");
    assert!(
        !ok,
        "`op thernthedu {{}}` must be a parse error without `syntax thamizh`"
    );
}

/// The thamizh-order recursion necks are depth-guarded too: a deep
/// `illaiyenil <cond> enil …` chain (well past `MAX_DEPTH` = 64) must fail with
/// a clean E1113, NOT abort the process with a stack overflow. This locks the
/// SEC-1 depth guard onto the Phase 1.8 thamizh if-expression path — the merge
/// of the security and grammar branches dropped it and it was restored. 200
/// levels is comfortably past the cap while staying small enough to avoid the
/// (separate) error-recovery rendering blow-up on a single huge line.
#[test]
fn deeply_nested_thamizh_else_if_errors_not_overflows() {
    let mut src = String::from("syntax thamizh\nmodule M {\n  in a: bit\n  out y: bit\n  y = ");
    for _ in 0..200 {
        src.push_str("a == 0 enil { 1 } illaiyenil ");
    }
    src.push_str("{ 0 }\n}\n");
    let (ok, stderr) = compile_src(&src, "deep_thamizh_elseif");
    assert!(!ok, "a 200-deep thamizh else-if chain must not compile");
    assert!(
        stderr.contains("E1113"),
        "expected a clean E1113 depth error (not a stack-overflow crash), got:\n{stderr}"
    );
}

/// The pure-Tamil-script, thamizh-order traffic light (an FSM exercising all
/// four flips at once — clocked block, conditional, if/else, and `match` over
/// an enum) emits byte-identical Verilog to its code-order Tamil twin. The
/// fixture was produced by `mimz translate --order thamizh --to tamil` and is
/// committed as a human-readable validation artifact (spec/04 Phase 1.8).
#[test]
fn traffic_light_tamil_thamizh_matches_code_order_twin() {
    let thamizh = compile(&fixture("traffic_light_tamil.thamizh.mimz"));
    let code_order = compile(&example("tamil/traffic_light.mimz"));
    assert_eq!(
        thamizh, code_order,
        "the Tamil thamizh-order traffic light must emit byte-identical Verilog to its twin"
    );
}

/// The profile boundary is symmetric: just as a trailing `enil`/`thernthedu` is
/// rejected in code order, a LEADING one (code-order syntax) inside a `syntax
/// thamizh` file must error — not silently parse as code order. Guards the
/// profile-aware dispatch in `primary`.
#[test]
fn code_order_if_is_rejected_in_thamizh() {
    let src = "syntax thamizh\nmodule M {\n  in a: bit\n  in b: bit\n  out y: bit\n  y = enil a { b } illaiyenil { a }\n}\n";
    let (ok, _stderr) = compile_src(src, "codeorder_if_in_thamizh");
    assert!(
        !ok,
        "a leading `enil` (code order) must be rejected inside a thamizh file"
    );
}
