//! Integration tests for the grammar engine (spec/04, Phase 1.8): the
//! `syntax thamizh` word-order profile.
//!
//! The headline guarantee is **same AST, two orders**. We test it the same
//! way the four-flavor rule is tested (`examples.rs`): the backend is
//! profile-blind, so a thamizh-order file and its code-order twin must emit
//! BYTE-IDENTICAL Verilog. Equal Verilog out of a profile-blind backend means
//! the parser built the same tree from both orders — which is the contract.
//!
//! Slice landed: the clocked-block flip (`rise(clk) on { }`). The conditional
//! / match / test flips arrive with the rest of Phase 1.8.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn mimz() -> Command {
    Command::new(env!("CARGO_BIN_EXE_mimz"))
}

/// Strip the `// Generated by mimz` banner line and normalize newlines, so
/// comparisons are over the Verilog body only (mirrors `examples.rs`).
fn strip_banner(v: &str) -> String {
    let mut lines = v.lines();
    let first = lines.next().unwrap_or("");
    if first.starts_with("// Generated by mimz") {
        let rest: Vec<&str> = lines.collect();
        format!("{}\n", rest.join("\n").trim_start_matches('\n'))
    } else {
        v.replace("\r\n", "\n")
    }
}

/// Compile a `.mimz` file to Verilog text. Unique temp path per call — tests
/// run in parallel and a shared output path is a torn-read race.
fn compile(path: &Path) -> String {
    static N: AtomicUsize = AtomicUsize::new(0);
    let name = path.display().to_string().replace(['\\', '/', ':'], "_");
    let out_v = std::env::temp_dir().join(format!(
        "mimz_grammar_{}_{name}.v",
        N.fetch_add(1, Ordering::Relaxed)
    ));
    let out = mimz()
        .arg("compile")
        .arg(path)
        .arg("-o")
        .arg(&out_v)
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "`mimz compile {}` failed:\n{}",
        path.display(),
        String::from_utf8_lossy(&out.stderr)
    );
    strip_banner(&std::fs::read_to_string(&out_v).unwrap())
}

/// Compile inline source from a temp file; return (success, stderr).
fn compile_src(src: &str, tag: &str) -> (bool, String) {
    static N: AtomicUsize = AtomicUsize::new(0);
    let n = N.fetch_add(1, Ordering::Relaxed);
    let in_f = std::env::temp_dir().join(format!("mimz_grammar_src_{tag}_{n}.mimz"));
    let out_v = std::env::temp_dir().join(format!("mimz_grammar_src_{tag}_{n}.v"));
    std::fs::write(&in_f, src).unwrap();
    let out = mimz()
        .arg("compile")
        .arg(&in_f)
        .arg("-o")
        .arg(&out_v)
        .output()
        .unwrap();
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

fn fixture(name: &str) -> PathBuf {
    root().join("tests/fixtures/grammar").join(name)
}

fn example(rel: &str) -> PathBuf {
    root().join("examples").join(rel)
}

/// Same-AST guarantee: the Tanglish thamizh-order counter compiles to the
/// EXACT same Verilog as its code-order twin (`examples/tanglish/counter`).
#[test]
fn thamizh_order_counter_matches_code_order_twin() {
    let thamizh = compile(&fixture("counter.thamizh.mimz"));
    let code_order = compile(&example("tanglish/counter.mimz"));
    assert_eq!(
        thamizh, code_order,
        "thamizh-order counter must emit byte-identical Verilog to its code-order twin"
    );
}

/// The pure-Tamil-script thamizh-order counter compiles to the same Verilog
/// as the code-order Tamil counter — Tamil script AND natural word order.
#[test]
fn thamizh_order_tamil_counter_matches_code_order_twin() {
    let thamizh = compile(&fixture("counter_tamil.thamizh.mimz"));
    let code_order = compile(&example("tamil/counter.mimz"));
    assert_eq!(thamizh, code_order);
}

/// Both thamizh-order flavors agree with the canonical English golden —
/// profile and keyword skin are fully orthogonal.
#[test]
fn thamizh_order_agrees_with_english_golden() {
    let english = compile(&example("english/counter.mimz"));
    assert_eq!(compile(&fixture("counter.thamizh.mimz")), english);
    assert_eq!(compile(&fixture("counter_tamil.thamizh.mimz")), english);
}

/// `syntax <other>` is rejected with E1112, not silently ignored.
#[test]
fn unknown_syntax_profile_is_an_error() {
    let (ok, stderr) = compile_src("syntax wibble\nmodule M { in a: bit\n}\n", "badprofile");
    assert!(!ok, "an unknown syntax profile must fail to compile");
    assert!(
        stderr.contains("E1112"),
        "expected E1112 for an unknown profile, got:\n{stderr}"
    );
}

/// In code-order (no directive) a leading `rise(...)` block is NOT accepted —
/// the flip is gated on the profile, not always on.
#[test]
fn flipped_on_block_is_rejected_in_code_order() {
    let src = "module M {\n  clock clk\n  reg r: bit = 0\n  rise(clk) on {\n    r <- r\n  }\n}\n";
    let (ok, _stderr) = compile_src(src, "flip_in_code");
    assert!(
        !ok,
        "`rise(clk) on {{}}` must be a parse error without `syntax thamizh`"
    );
}
