//! Golden Verilog snapshot tests for the IR Verilog backend (synthesis v1,
//! phase 1, Task 3).
//!
//! For the same five `.mimz` sources as `tests/ir_golden.rs`, compile through
//! load -> check -> elaborate (`SimMode::Lower`) -> lower -> optimize ->
//! `backend::verilog::emit` and lock the text against
//! `tests/golden/ir_verilog/<name>.v`.
//!
//! The first line is a version banner (`// Generated by mimz <version> ...`)
//! that changes every release, so it is stripped before comparing (and the
//! golden files hold the stripped text).
//!
//! To regenerate after an INTENDED backend change:
//! `MIMZ_UPDATE_GOLDENS=1 cargo test --test ir_verilog_golden` - then review
//! the diff like any other code change.

use std::path::PathBuf;

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn check_golden(example_path: &str, golden_path: &str) {
    let update = std::env::var("MIMZ_UPDATE_GOLDENS").is_ok();

    let full_path = repo().join(example_path);
    let files = match mimz::project::load_project(&full_path) {
        Ok(files) => files,
        // `LoadError` intentionally has no `Debug`; see tests/stdlib.rs.
        Err(_) => panic!("failed to load {}", full_path.display()),
    };
    let asts: Vec<mimz_core::ast::File> = files.iter().map(|f| f.ast.clone()).collect();
    if let Err(errors) = mimz_core::checker::check(&asts) {
        panic!("{} failed checking: {errors:?}", full_path.display());
    }
    let design = mimz_core::elaborate::elaborate_project_with_mode(
        &asts,
        None,
        &Default::default(),
        mimz_core::elaborate::SimMode::Lower,
    )
    .unwrap_or_else(|e| panic!("{} failed to elaborate: {e:?}", full_path.display()));
    let mut module = mimz_core::ir::lower(&design);
    mimz_core::ir::opt::optimize(&mut module);
    let full = mimz_core::backend::verilog::emit(&module).text;
    assert!(
        full.starts_with("// Generated by mimz "),
        "unexpected banner: {}",
        full.lines().next().unwrap_or("")
    );
    let text = full.split_once('\n').unwrap().1;

    let golden_full = repo().join(golden_path);
    if update {
        std::fs::create_dir_all(golden_full.parent().unwrap()).unwrap();
        std::fs::write(&golden_full, text).unwrap();
        return;
    }
    let want = std::fs::read_to_string(&golden_full)
        .unwrap_or_else(|_| {
            panic!(
                "missing golden {} - run with MIMZ_UPDATE_GOLDENS=1 to create it",
                golden_full.display()
            )
        })
        .replace("\r\n", "\n");
    assert_eq!(
        text, want,
        "Verilog for {example_path} drifted from {golden_path} - if this is an intentional \
         backend change, regenerate with `MIMZ_UPDATE_GOLDENS=1 cargo test --test ir_verilog_golden` \
         and review the diff"
    );
}

#[test]
fn adder_example_matches_golden_verilog() {
    check_golden(
        "examples/english/adder.mimz",
        "tests/golden/ir_verilog/adder.v",
    );
}

#[test]
fn mux4_example_matches_golden_verilog() {
    check_golden(
        "examples/english/mux4.mimz",
        "tests/golden/ir_verilog/mux4.v",
    );
}

#[test]
fn pll_extern_example_matches_golden_verilog() {
    check_golden(
        "tests/fixtures/extern/pll.mimz",
        "tests/golden/ir_verilog/pll.v",
    );
}

#[test]
fn async_reset_example_matches_golden_verilog() {
    check_golden(
        "examples/english/async_reset.mimz",
        "tests/golden/ir_verilog/async_reset.v",
    );
}

#[test]
fn regfile_example_matches_golden_verilog() {
    check_golden(
        "examples/english/regfile.mimz",
        "tests/golden/ir_verilog/regfile.v",
    );
}
