use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

static UNIQ: AtomicUsize = AtomicUsize::new(0);

#[test]
fn wasm_produces_identical_verilog_to_cli() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let pkg_dir = manifest_dir.join("crates").join("mimz-wasm").join("pkg");
    if !pkg_dir.exists() {
        eprintln!("skipping WASM parity test: mimz-wasm pkg not built");
        return;
    }

    let counter_path = manifest_dir
        .join("examples")
        .join("english")
        .join("counter.mimz");
    let counter_src = fs::read_to_string(&counter_path).unwrap();

    let uniq = UNIQ.fetch_add(1, Ordering::Relaxed);
    let out_v = std::env::temp_dir().join(format!("mimz_parity_{uniq}.v"));

    let cli_out = Command::new(env!("CARGO_BIN_EXE_mimz"))
        .arg("compile")
        .arg(&counter_path)
        .arg("-o")
        .arg(&out_v)
        .output()
        .unwrap();
    assert!(
        cli_out.status.success(),
        "CLI failed: {}",
        String::from_utf8_lossy(&cli_out.stderr)
    );
    let mut cli_v = fs::read_to_string(&out_v).unwrap();
    let _ = fs::remove_file(&out_v);

    if let Some(pos) = cli_v.find('\n') {
        if cli_v.starts_with("// Generated by mimz") {
            cli_v = cli_v[pos + 1..].to_string();
        }
    }

    let node_script = format!(
        r#"
const {{ compileToVerilog }} = require('{}/mimz_wasm.js');
const src = {};
try {{
    console.log(compileToVerilog(src));
}} catch(e) {{
    console.error(e.message);
    process.exit(1);
}}
"#,
        pkg_dir.display().to_string().replace('\\', "/"),
        serde_json::to_string(&counter_src).unwrap()
    );

    let node_out = Command::new("node")
        .arg("-e")
        .arg(&node_script)
        .output()
        .unwrap();

    assert!(
        node_out.status.success(),
        "WASM compile failed: {}",
        String::from_utf8_lossy(&node_out.stderr)
    );
    let mut wasm_v = String::from_utf8(node_out.stdout).unwrap();

    if let Some(pos) = wasm_v.find('\n') {
        if wasm_v.starts_with("// Generated by mimz") {
            wasm_v = wasm_v[pos + 1..].to_string();
        }
    }

    assert_eq!(
        cli_v.replace("\r\n", "\n").trim(),
        wasm_v.replace("\r\n", "\n").trim(),
        "WASM output differs from CLI output"
    );
}
