use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn all_mimz_files(root: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|e| e == "mimz") {
                    files.push(path);
                }
            }
        }
    }
    files.sort();
    files
}

fn run_parity(dir: &str) {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let pkg_dir = manifest_dir.join("crates").join("mimz-wasm").join("pkg");
    if !pkg_dir.exists() {
        eprintln!("skipping WASM parity test: mimz-wasm pkg not built");
        return;
    }

    let search_dir = manifest_dir.join(dir);
    let mut all_files = Vec::new();
    for path in all_mimz_files(&search_dir) {
        let src = fs::read_to_string(&path).unwrap();
        all_files.push((path, src));
    }

    let mut script = format!(
        "import fs from 'fs';\nimport init, {{ compileToVerilog, runCommand }} from 'file:///{}';\nconst wasmBuffer = fs.readFileSync('{}');\nawait init({{ module_or_path: wasmBuffer }});\n",
        pkg_dir
            .join("mimz_wasm.js")
            .display()
            .to_string()
            .replace('\\', "/"),
        pkg_dir
            .join("mimz_wasm_bg.wasm")
            .display()
            .to_string()
            .replace('\\', "/")
    );
    script.push_str("const results = [];\n");

    for (i, (_, src)) in all_files.iter().enumerate() {
        let src_json = serde_json::to_string(src).unwrap();
        script.push_str(&format!(
            r#"
try {{
    let compileOut = "";
    let checkOut = "";
    try {{ compileOut = compileToVerilog({src_json}); }} catch(e) {{ compileOut = "ERR: " + e.message; }}
    try {{ checkOut = runCommand({src_json}, "check", []); }} catch(e) {{ checkOut = "ERR: " + e.message; }}
    results.push({{ idx: {i}, compile: compileOut, check: checkOut }});
}} catch(e) {{
    console.error("Fatal error on idx {i}:", e.message);
    process.exit(1);
}}
"#,
            src_json = src_json,
            i = i
        ));
    }
    script.push_str("console.log(JSON.stringify(results));\n");

    let tmp_script = std::env::temp_dir().join(format!(
        "mimz_wasm_{}_{}.mjs",
        dir.replace('/', "_"),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::write(&tmp_script, &script).unwrap();

    let node_out = Command::new("node").arg(&tmp_script).output().unwrap();

    let _ = fs::remove_file(&tmp_script);

    assert!(
        node_out.status.success(),
        "WASM Node script failed: {}",
        String::from_utf8_lossy(&node_out.stderr)
    );

    let wasm_results: Vec<serde_json::Value> = serde_json::from_slice(&node_out.stdout).unwrap();

    for (i, (path, _src)) in all_files.iter().enumerate() {
        let wasm_res = &wasm_results[i];
        let wasm_compile_str = wasm_res["compile"].as_str().unwrap().to_string();
        if wasm_compile_str
            .contains("`import` is not supported when compiling a single in-memory source")
        {
            continue;
        }

        // 1. CLI compile string
        let out_v =
            std::env::temp_dir().join(format!("mimz_parity_{}_{}.v", dir.replace('/', "_"), i));
        let cli_compile = Command::new(env!("CARGO_BIN_EXE_mimz"))
            .arg("compile")
            .arg(path)
            .arg("-o")
            .arg(&out_v)
            .output()
            .unwrap();

        let mut cli_compile_str = if cli_compile.status.success() {
            fs::read_to_string(&out_v).unwrap_or_default()
        } else {
            format!("ERR: {}", String::from_utf8_lossy(&cli_compile.stderr))
        };
        let _ = fs::remove_file(&out_v);

        // Strip the generated header for comparison
        if let Some(pos) = cli_compile_str.find('\n') {
            if cli_compile_str.starts_with("// Generated by mimz") {
                cli_compile_str = cli_compile_str[pos + 1..].to_string();
            }
        }

        let mut wasm_compile_str = wasm_res["compile"].as_str().unwrap().to_string();
        if let Some(pos) = wasm_compile_str.find('\n') {
            if wasm_compile_str.starts_with("// Generated by mimz") {
                wasm_compile_str = wasm_compile_str[pos + 1..].to_string();
            }
        }

        assert_eq!(
            cli_compile_str.replace("\r\n", "\n").trim(),
            wasm_compile_str.replace("\r\n", "\n").trim(),
            "compile parity failed for {}",
            path.display()
        );

        // 2. CLI check
        let cli_check = Command::new(env!("CARGO_BIN_EXE_mimz"))
            .arg("check")
            .arg(path)
            .output()
            .unwrap();

        let cli_check_str = if cli_check.status.success() {
            String::from_utf8_lossy(&cli_check.stdout).to_string()
        } else {
            format!("ERR: {}", String::from_utf8_lossy(&cli_check.stderr))
        };

        let wasm_check_str = wasm_res["check"].as_str().unwrap().to_string();

        if cli_check_str.starts_with("OK") {
            assert!(
                wasm_check_str.starts_with("OK"),
                "wasm check failed for {}: {}",
                path.display(),
                wasm_check_str
            );
        } else {
            assert_eq!(
                cli_check_str.replace("\r\n", "\n").trim(),
                wasm_check_str.replace("\r\n", "\n").trim(),
                "check parity failed for {}",
                path.display()
            );
        }
    }
}

#[test]
fn all_examples_work_in_wasm() {
    run_parity("examples");
}

#[test]
fn all_showcase_work_in_wasm() {
    run_parity("showcase");
}
