use std::fs;
use std::path::PathBuf;
use std::process::Command;

const BASE_EXAMPLES: [&str; 38] = [
    "adder",
    "alu",
    "async_reset",
    "bitops",
    "blinker",
    "chained",
    "comparator",
    "counter",
    "datapath",
    "dual_edge",
    "edge_detector",
    "fn_array_search",
    "fn_const_local",
    "fn_mac",
    "fn_mac_local",
    "fn_return_guard",
    "fn_with_const",
    "lib/full_adder",
    "mux4",
    "std/debouncer",
    "std/seg7",
    "std/pwm",
    "std/fifo",
    "std/uart_tx",
    "priority",
    "pulse_gen",
    "regfile",
    "replicate",
    "ripple_adder",
    "shift_register",
    "shift",
    "signed_math",
    "traffic_light",
    "vilakku",
    "window",
    "tested_adder",
    "tagged_packet",
    "debug_wrapper",
];

const SHOWCASE_EXAMPLES: [&str; 5] = [
    "can_frame_filter",
    "melody_player",
    "pid_controller",
    "uart_echo",
    "vga_pattern",
];

fn run_parity(dir: &str, names: &[&str]) {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let pkg_dir = manifest_dir.join("crates").join("mimz-wasm").join("pkg");
    if !pkg_dir.exists() {
        eprintln!("skipping WASM parity test: mimz-wasm pkg not built");
        return;
    }

    let mut all_files = Vec::new();
    for name in names {
        let path = manifest_dir.join(dir).join(format!("{}.mimz", name));
        let src = fs::read_to_string(&path).unwrap();
        all_files.push((path, src));
    }

    let mut script = format!(
        "import fs from 'fs';\nimport init, {{ compileToVerilog, runCommand }} from 'file:///{}';\nconst wasmBuffer = fs.readFileSync('{}');\nawait init({{ module_or_path: wasmBuffer }});\n",
        pkg_dir
            .join("mimz_wasm.js")
            .display()
            .to_string()
            .replace('\\', "/"),
        pkg_dir
            .join("mimz_wasm_bg.wasm")
            .display()
            .to_string()
            .replace('\\', "/")
    );
    script.push_str("const results = [];\n");

    for (i, (_, src)) in all_files.iter().enumerate() {
        let src_json = serde_json::to_string(src).unwrap();
        script.push_str(&format!(
            r#"
try {{
    let compileOut = "";
    let checkOut = "";
    try {{ compileOut = compileToVerilog({src_json}); }} catch(e) {{ compileOut = "ERR: " + e.message; }}
    try {{ checkOut = runCommand({src_json}, "check", []); }} catch(e) {{ checkOut = "ERR: " + e.message; }}
    results.push({{ idx: {i}, compile: compileOut, check: checkOut }});
}} catch(e) {{
    console.error("Fatal error on idx {i}:", e.message);
    process.exit(1);
}}
"#,
            src_json = src_json,
            i = i
        ));
    }
    script.push_str("console.log(JSON.stringify(results));\n");

    let tmp_script = std::env::temp_dir().join(format!(
        "mimz_wasm_{}_{}.mjs",
        dir.replace('/', "_"),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::write(&tmp_script, &script).unwrap();

    let node_out = Command::new("node").arg(&tmp_script).output().unwrap();

    let _ = fs::remove_file(&tmp_script);

    assert!(
        node_out.status.success(),
        "WASM Node script failed: {}",
        String::from_utf8_lossy(&node_out.stderr)
    );

    let wasm_results: Vec<serde_json::Value> = serde_json::from_slice(&node_out.stdout).unwrap();

    for (i, (path, src)) in all_files.iter().enumerate() {
        let wasm_res = &wasm_results[i];
        let has_import = src.contains("import ")
            || src.contains("include ")
            || src.contains("serkka ")
            || src.contains("சேர்க்க ");

        if has_import {
            let wasm_compile_str = wasm_res["compile"].as_str().unwrap().to_string();
            assert!(
                wasm_compile_str
                    .contains("`import` is not supported when compiling a single in-memory source"),
                "WASM did not reject import gracefully for {}: {}",
                path.display(),
                wasm_compile_str
            );
            continue;
        }

        // 1. CLI compile string
        let out_v =
            std::env::temp_dir().join(format!("mimz_parity_{}_{}.v", dir.replace('/', "_"), i));
        let cli_compile = Command::new(env!("CARGO_BIN_EXE_mimz"))
            .arg("compile")
            .arg(path)
            .arg("-o")
            .arg(&out_v)
            .output()
            .unwrap();

        let mut cli_compile_str = if cli_compile.status.success() {
            fs::read_to_string(&out_v).unwrap_or_default()
        } else {
            format!("ERR: {}", String::from_utf8_lossy(&cli_compile.stderr))
        };
        let _ = fs::remove_file(&out_v);

        // Strip the generated header for comparison
        if let Some(pos) = cli_compile_str.find('\n') {
            if cli_compile_str.starts_with("// Generated by mimz") {
                cli_compile_str = cli_compile_str[pos + 1..].to_string();
            }
        }

        let mut wasm_compile_str = wasm_res["compile"].as_str().unwrap().to_string();
        if let Some(pos) = wasm_compile_str.find('\n') {
            if wasm_compile_str.starts_with("// Generated by mimz") {
                wasm_compile_str = wasm_compile_str[pos + 1..].to_string();
            }
        }

        assert_eq!(
            cli_compile_str.replace("\r\n", "\n").trim(),
            wasm_compile_str.replace("\r\n", "\n").trim(),
            "compile parity failed for {}",
            path.display()
        );

        // 2. CLI check
        let cli_check = Command::new(env!("CARGO_BIN_EXE_mimz"))
            .arg("check")
            .arg(path)
            .output()
            .unwrap();

        let cli_check_str = if cli_check.status.success() {
            String::from_utf8_lossy(&cli_check.stdout).to_string()
        } else {
            format!("ERR: {}", String::from_utf8_lossy(&cli_check.stderr))
        };

        let wasm_check_str = wasm_res["check"].as_str().unwrap().to_string();

        if cli_check_str.starts_with("OK") {
            assert!(
                wasm_check_str.starts_with("OK"),
                "wasm check failed for {}: {}",
                path.display(),
                wasm_check_str
            );
        } else {
            assert_eq!(
                cli_check_str.replace("\r\n", "\n").trim(),
                wasm_check_str.replace("\r\n", "\n").trim(),
                "check parity failed for {}",
                path.display()
            );
        }
    }
}

#[test]
fn all_base_examples_work_in_wasm() {
    run_parity("examples/english", &BASE_EXAMPLES);
}

#[test]
fn all_showcase_examples_work_in_wasm() {
    run_parity("showcase/english", &SHOWCASE_EXAMPLES);
}
