//! IR -> structural Verilog-2005 (synthesis v1, phase 1; design doc
//! section 4). One flat module, one statement per cell.
//!
//! Nothing relies on Verilog's context-dependent width or sign rules (the
//! source of BUG-24/34/52/55 in the AST emitter): an arithmetic operand is
//! widened here to the width its cell computes at, with the signedness
//! `ir::exec` uses for that cell.

use super::{Source, drivers, legal_name, output_pins};
use crate::ast::{Dir, Edge};
use crate::bits::to_decimal_string;
use crate::checker::consteval::ConstVal;
use crate::emit_verilog::ProjectNames;
use crate::emit_verilog::translit::NameAllocator;
use crate::ir::{Bits, Cell, CellKind, Module, NetId};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt::Write;

/// The emitted module and the Verilog name of each IR port.
pub struct Emitted {
    /// Verilog-2005 source: one module, no includes.
    pub text: String,
    /// The emitted module's name.
    pub top: String,
    /// `(IR port name, Verilog port name, width, direction)`, in port order.
    pub ports: Vec<(String, String, u32, Dir)>,
}

/// Deepest memory emitted as a Verilog array.
const MAX_MEM_DEPTH: u128 = 1 << 20;

/// Emits a validated, flat `module` as one Verilog-2005 module. An
/// unsupported construct is reported with `ir::failure::limitation`.
///
/// An extern's module, parameter and pin names are allocated among the extern's
/// own names only; use [`emit_with_names`] to spell them exactly as `mimz
/// compile` does.
pub fn emit(module: &Module) -> Emitted {
    emit_impl(module, None)
}

/// Like [`emit`], but an extern's (un-aliased) module, parameter and pin names
/// come from the project-wide name map `mimz compile` uses
/// ([`crate::emit_verilog::project_names`]), so the user's companion `.v`
/// matches both paths even when a project name already took a spelling.
pub fn emit_with_names(module: &Module, names: &ProjectNames) -> Emitted {
    emit_impl(module, Some(names))
}

fn emit_impl(module: &Module, project: Option<&ProjectNames>) -> Emitted {
    Emitter {
        project,
        m: module,
        drivers: drivers(module),
        used: HashSet::new(),
        port_names: Vec::new(),
        outs: HashMap::new(),
        decls: String::new(),
        body: String::new(),
    }
    .run()
}

struct Emitter<'a> {
    project: Option<&'a ProjectNames>,
    m: &'a Module,
    drivers: HashMap<NetId, Source>,
    used: HashSet<String>,
    port_names: Vec<String>,
    /// Verilog name and width of each cell output vector, by (cell, pin).
    outs: HashMap<(usize, String), (String, u32)>,
    decls: String,
    body: String,
}

fn range(w: u32) -> String {
    if w == 0 {
        crate::ir::failure::limitation("a zero-width port or net has no Verilog spelling".into());
    }
    if w == 1 {
        String::new()
    } else {
        format!("[{}:0] ", w - 1)
    }
}

fn edge_kw(e: Edge) -> &'static str {
    match e {
        Edge::Rise => "posedge",
        Edge::Fall => "negedge",
    }
}

fn literal(v: &ConstVal) -> String {
    format!("{}'d{}", v.width, to_decimal_string(&v.bits))
}

impl Emitter<'_> {
    fn run(mut self) -> Emitted {
        let m = self.m;
        self.port_names = m
            .ports
            .iter()
            .map(|(n, _, _)| legal_name(n, &mut self.used))
            .collect();
        for (c, cell) in m.cells.iter().enumerate() {
            let is_reg = matches!(cell.kind, CellKind::Dff { .. } | CellKind::Adff { .. });
            for (pin, bits) in output_pins(m, cell) {
                let name = legal_name(&self.base_name(c, cell, &pin, bits), &mut self.used);
                let (kw, init) = if is_reg {
                    ("reg", " = 0")
                } else {
                    ("wire", "")
                };
                writeln!(self.decls, "    {kw} {}{name}{init};", range(bits.width())).unwrap();
                self.outs.insert((c, pin), (name, bits.width()));
            }
        }
        for (c, cell) in m.cells.iter().enumerate() {
            self.cell(c, cell);
        }
        for (p, (_, bits, dir)) in m.ports.iter().enumerate() {
            if *dir == Dir::Out {
                let e = self.read(bits);
                writeln!(self.body, "    assign {} = {e};", self.port_names[p]).unwrap();
            }
        }
        let top = legal_name(&m.name, &mut HashSet::new());
        let header: Vec<String> = m
            .ports
            .iter()
            .zip(&self.port_names)
            .map(|((_, b, d), n)| {
                let dir = if *d == Dir::In { "input" } else { "output" };
                format!("    {dir} wire {}{n}", range(b.width()))
            })
            .collect();
        let text = format!(
            "// Generated by mimz {} from the Min-Mozhi IR. Do not edit.\nmodule {top} (\n{}\n);\n{}{}endmodule\n",
            crate::version::COMPILER_VERSION,
            header.join(",\n"),
            self.decls,
            self.body
        );
        let ports = m
            .ports
            .iter()
            .zip(self.port_names)
            .map(|((n, b, d), v)| (n.clone(), v, b.width(), *d))
            .collect();
        Emitted { text, top, ports }
    }

    /// The source name when every net of the vector carries the same one,
    /// else `c<idx>_<kind>` (`_<pin>` added for multi-output cells).
    fn base_name(&self, c: usize, cell: &Cell, pin: &str, bits: &Bits) -> String {
        let name_of = |n: &NetId| self.m.nets[n.0 as usize].name.as_deref();
        if let Some(first) = bits.nets.first().and_then(name_of)
            && bits.nets.iter().all(|n| name_of(n) == Some(first))
        {
            return first.to_string();
        }
        let kind: String = format!("{:?}", cell.kind)
            .chars()
            .take_while(|ch| ch.is_alphanumeric())
            .collect::<String>()
            .to_lowercase();
        if pin == "out" || pin == "q" {
            format!("c{c}_{kind}")
        } else {
            format!("c{c}_{kind}_{pin}")
        }
    }

    /// The Verilog vector holding net `n`, the bit index there, the width.
    fn locate(&self, n: NetId) -> (String, u32, u32) {
        match self.drivers.get(&n) {
            Some(Source::Port { port, bit }) => (
                self.port_names[*port].clone(),
                *bit,
                self.m.ports[*port].1.width(),
            ),
            Some(Source::Cell { cell, pin, bit }) => {
                let (name, w) = &self.outs[&(*cell, pin.clone())];
                (name.clone(), *bit, *w)
            }
            None => panic!("net {} has no driver (validate guarantees one)", n.0),
        }
    }

    /// `bits` as a Verilog expression, MSB first: a whole vector by name, a
    /// run of consecutive bits as a part-select, joined by a concatenation.
    fn read(&self, bits: &Bits) -> String {
        if bits.nets.is_empty() {
            return "1'b0".to_string();
        }
        // (vector, lo, hi, vector width), LSB first.
        let mut runs: Vec<(String, u32, u32, u32)> = Vec::new();
        for n in &bits.nets {
            let (v, bit, w) = self.locate(*n);
            match runs.last_mut() {
                Some(r) if r.0 == v && r.2 + 1 == bit => r.2 = bit,
                _ => runs.push((v, bit, bit, w)),
            }
        }
        let parts: Vec<String> = runs
            .iter()
            .rev()
            .map(|(v, lo, hi, w)| {
                if *lo == 0 && hi + 1 == *w {
                    v.clone()
                } else if lo == hi {
                    format!("{v}[{lo}]")
                } else {
                    format!("{v}[{hi}:{lo}]")
                }
            })
            .collect();
        if parts.len() == 1 {
            parts.into_iter().next().unwrap()
        } else {
            format!("{{{}}}", parts.join(", "))
        }
    }

    /// `bits` widened to `w` bits: sign-extended when `signed`, else
    /// zero-extended. Never narrows.
    fn widen(&self, bits: &Bits, w: u32, signed: bool) -> String {
        let e = self.read(bits);
        let have = bits.width();
        if have >= w {
            return e;
        }
        let k = w - have;
        if signed {
            let Some(last) = bits.nets.last() else {
                crate::ir::failure::limitation("cannot sign-extend a zero-width operand".into());
            };
            let msb = self.read(&Bits::unsigned(vec![*last]));
            format!("{{{{{k}{{{msb}}}}}, {e}}}")
        } else {
            format!("{{{k}'b0, {e}}}")
        }
    }

    fn cmp(&self, op: &str, signed: bool, p: &BTreeMap<&'static str, Bits>) -> String {
        let (a, b) = (self.read(&p["a"]), self.read(&p["b"]));
        if signed {
            format!("$signed({a}) {op} $signed({b})")
        } else {
            format!("{a} {op} {b}")
        }
    }

    fn assign(&mut self, c: usize, pin: &str, expr: String) {
        let name = &self.outs[&(c, pin.to_string())].0;
        writeln!(self.body, "    assign {name} = {expr};").unwrap();
    }

    fn cell(&mut self, c: usize, cell: &Cell) {
        let p = &cell.pins;
        let rd = |s: &Self, pin: &str| s.read(&p[pin]);
        // `ir::exec::arith`: signed when either operand pin is, for both.
        let arith = |s: &Self, op: &str| {
            let signed = p["a"].signed || p["b"].signed;
            let w = p["out"].width();
            format!(
                "{} {op} {}",
                s.widen(&p["a"], w, signed),
                s.widen(&p["b"], w, signed)
            )
        };
        // Verilog widens `a` of a bitwise op to the target width before
        // operating; `ir::exec` does not, so a wider `out` must not slip through.
        if matches!(
            cell.kind,
            CellKind::Not | CellKind::And | CellKind::Or | CellKind::Xor
        ) && p["out"].width() != p["a"].width()
        {
            crate::ir::failure::limitation(format!(
                "cell {c}: bitwise cell output is {} bits but its operand is {}",
                p["out"].width(),
                p["a"].width()
            ));
        }
        let e = match &cell.kind {
            CellKind::Add | CellKind::AddWrap => arith(self, "+"),
            CellKind::Sub | CellKind::SubWrap => arith(self, "-"),
            CellKind::Mul | CellKind::MulWrap => arith(self, "*"),
            // `ir::exec` shifts the operand read unsigned (zero-extended).
            CellKind::Shl => format!(
                "{} << {}",
                self.widen(&p["a"], p["out"].width(), false),
                rd(self, "b")
            ),
            CellKind::Shr => format!("{} >> {}", rd(self, "a"), rd(self, "b")),
            CellKind::And => format!("{} & {}", rd(self, "a"), rd(self, "b")),
            CellKind::Or => format!("{} | {}", rd(self, "a"), rd(self, "b")),
            CellKind::Xor => format!("{} ^ {}", rd(self, "a"), rd(self, "b")),
            CellKind::Not => format!("~{}", rd(self, "a")),
            CellKind::RedAnd => format!("&{}", rd(self, "a")),
            CellKind::RedOr => format!("|{}", rd(self, "a")),
            CellKind::RedXor => format!("^{}", rd(self, "a")),
            // `ir::exec` negates the operand as signed.
            CellKind::Neg => format!("-{}", self.widen(&p["a"], p["out"].width(), true)),
            CellKind::Eq => format!("{} == {}", rd(self, "a"), rd(self, "b")),
            CellKind::Ne => format!("{} != {}", rd(self, "a"), rd(self, "b")),
            CellKind::Lt { signed } => self.cmp("<", *signed, p),
            CellKind::Le { signed } => self.cmp("<=", *signed, p),
            CellKind::Gt { signed } => self.cmp(">", *signed, p),
            CellKind::Ge { signed } => self.cmp(">=", *signed, p),
            CellKind::LogicAnd => format!("(|{}) && (|{})", rd(self, "a"), rd(self, "b")),
            CellKind::LogicOr => format!("(|{}) || (|{})", rd(self, "a"), rd(self, "b")),
            CellKind::LogicNot => format!("!(|{})", rd(self, "a")),
            CellKind::Mux => format!(
                "{} ? {} : {}",
                rd(self, "sel"),
                rd(self, "a"),
                rd(self, "b")
            ),
            CellKind::Concat => {
                let nets = p
                    .iter()
                    .filter(|(n, _)| **n != "out")
                    .flat_map(|(_, b)| b.nets.iter().copied())
                    .collect();
                self.read(&Bits::unsigned(nets))
            }
            CellKind::Slice { lo, hi } => self.read(&Bits::unsigned(
                p["a"].nets[*lo as usize..=*hi as usize].to_vec(),
            )),
            CellKind::Const { value } => literal(value),
            CellKind::Dff { clock, edge } => return self.register(c, cell, *clock, *edge, None),
            CellKind::Adff { clock, edge, value } => {
                return self.register(c, cell, *clock, *edge, Some(value));
            }
            CellKind::Mem { .. } => return self.memory(c, cell),
            CellKind::BlackBox { .. } => return self.black_box(c, cell),
        };
        self.assign(c, "out", e);
    }

    fn register(
        &mut self,
        c: usize,
        cell: &Cell,
        clock: NetId,
        edge: Edge,
        reset: Option<&ConstVal>,
    ) {
        let q = self.outs[&(c, "q".to_string())].0.clone();
        let d = self.read(&cell.pins["d"]);
        let clk = self.read(&Bits::unsigned(vec![clock]));
        let ev = edge_kw(edge);
        match reset {
            None => writeln!(self.body, "    always @({ev} {clk}) {q} <= {d};"),
            Some(v) => {
                let arst = self.read(&cell.pins["arst"]);
                writeln!(
                    self.body,
                    "    always @({ev} {clk} or posedge {arst})\n        if ({arst}) {q} <= {};\n        else {q} <= {d};",
                    literal(v)
                )
            }
        }
        .unwrap();
    }

    fn memory(&mut self, c: usize, cell: &Cell) {
        let CellKind::Mem {
            depth,
            init,
            read_ports,
            edge,
        } = &cell.kind
        else {
            unreachable!("memory() is only called for a Mem cell")
        };
        if *depth > MAX_MEM_DEPTH {
            crate::ir::failure::limitation(format!(
                "memory of depth {depth} is deeper than the Verilog backend emits ({MAX_MEM_DEPTH})"
            ));
        }
        let w = read_ports
            .first()
            .map(|(_, r)| r.width())
            .unwrap_or_else(|| cell.pins["wdata"].width());
        let arr = legal_name(&format!("mem{c}"), &mut self.used);
        // `ir::exec` seeds with `from_const_at_width(init, w, false)`.
        let iv = crate::value::from_const_at_width(init, w, false);
        let init_lit = format!("{w}'d{}", to_decimal_string(&iv.bits));
        let i = legal_name(&format!("{arr}_i"), &mut self.used);
        writeln!(self.decls, "    reg {}{arr} [0:{}];", range(w), depth - 1).unwrap();
        writeln!(
            self.decls,
            "    integer {i};\n    initial for ({i} = 0; {i} < {depth}; {i} = {i} + 1) {arr}[{i}] = {init_lit};"
        )
        .unwrap();
        // A ROM has no `clock` pin and no write port to emit.
        if let Some(clock) = cell.pins.get("clock") {
            let clk = self.read(clock);
            let (wen, waddr, wdata) = (
                self.read(&cell.pins["wen"]),
                self.read(&cell.pins["waddr"]),
                self.read(&cell.pins["wdata"]),
            );
            writeln!(
                self.body,
                "    always @({} {clk}) if ({wen}) {arr}[{waddr}] <= {wdata};",
                edge_kw(*edge)
            )
            .unwrap();
        }
        for (n, (raddr, _)) in read_ports.iter().enumerate() {
            let a = self.read(raddr);
            // `ir::exec` reads `init` past the end; plain Verilog reads X.
            let every_address_exists = raddr.width() < 128 && (1u128 << raddr.width()) <= *depth;
            let e = if every_address_exists {
                format!("{arr}[{a}]")
            } else {
                format!("({a} < {depth}) ? {arr}[{a}] : {init_lit}")
            };
            self.assign(c, &format!("rdata{n}"), e);
        }
    }

    fn black_box(&mut self, c: usize, cell: &Cell) {
        let CellKind::BlackBox {
            module_name,
            verilog_name,
            aliased,
            params,
        } = &cell.kind
        else {
            unreachable!("black_box() is only called for a BlackBox cell")
        };
        // Spell the Min-Mozhi-facing names (module, parameters, pins) exactly as
        // the AST emitter does, with the same allocator (romanized, `_2` on a
        // clash, reserved words avoided), so the user's companion `.v` matches
        // both paths. An explicit `= "alias"` is kept verbatim. Allocation
        // order is the AST pass's: module, parameters, then ports in declaration
        // order (the IR keeps ports only in `extern_decls`, so a clock/reset,
        // which it lacks, comes last).
        let declared: Vec<&str> = self
            .m
            .extern_decls
            .get(module_name)
            .map(|d| d.iter().map(|(n, ..)| n.as_str()).collect())
            .unwrap_or_default();
        let mut pin_order: Vec<&str> = declared
            .iter()
            .filter(|n| cell.pins.contains_key(**n))
            .copied()
            .collect();
        pin_order.extend(cell.pins.keys().filter(|p| !declared.contains(*p)));
        // With a project name map (`mimz build`) the spelling is exactly
        // `mimz compile`'s; without one, allocate among this extern's names.
        let project = self.project;
        let mut names = NameAllocator::new();
        for n in std::iter::once(module_name.as_str())
            .chain(params.iter().map(|(n, _)| n.as_str()))
            .chain(pin_order.iter().copied())
        {
            names.claim(n);
        }
        let mut spell = |n: &str| match project {
            Some(p) => p.get(n),
            None => names.allocate(n),
        };
        let module_v = spell(module_name);
        let param_names: Vec<String> = params.iter().map(|(n, _)| spell(n)).collect();
        let pin_names: HashMap<&str, String> = pin_order.iter().map(|p| (*p, spell(p))).collect();
        let verilog_name = if *aliased {
            verilog_name.clone()
        } else {
            module_v
        };
        let outs: HashMap<String, String> = output_pins(self.m, cell)
            .into_iter()
            .map(|(p, _)| {
                let v = self.outs[&(c, p.clone())].0.clone();
                (p, v)
            })
            .collect();
        let conns: Vec<String> = cell
            .pins
            .iter()
            .map(|(pin, bits)| {
                let e = outs.get(*pin).cloned().unwrap_or_else(|| self.read(bits));
                format!(".{}({e})", pin_names[pin])
            })
            .collect();
        let ps = if params.is_empty() {
            String::new()
        } else {
            let items: Vec<String> = params
                .iter()
                .zip(&param_names)
                .map(|((_, v), n)| format!(".{n}({v})"))
                .collect();
            format!(" #({})", items.join(", "))
        };
        let inst = legal_name(&format!("u{c}"), &mut self.used);
        writeln!(
            self.body,
            "    {verilog_name}{ps} {inst} ({});",
            conns.join(", ")
        )
        .unwrap();
    }
}
